set_property -dict { PACKAGE_PIN J15  IOSTANDARD SSTL15 } [get_ports { D[0] }];

set_property -dict { PACKAGE_PIN AE20  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[0]
set_property -dict { PACKAGE_PIN AG20  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[1]
set_property -dict { PACKAGE_PIN AF20  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[2]
set_property -dict { PACKAGE_PIN AE22  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[3]
set_property -dict { PACKAGE_PIN AD20  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[4]
set_property -dict { PACKAGE_PIN AG22  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[5]
set_property -dict { PACKAGE_PIN AF22  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[6]
set_property -dict { PACKAGE_PIN AE23  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[7]
set_property -dict { PACKAGE_PIN AF24  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[8]
set_property -dict { PACKAGE_PIN AJ23  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[9]
set_property -dict { PACKAGE_PIN AF23  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[10]
set_property -dict { PACKAGE_PIN AH23  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[11]
set_property -dict { PACKAGE_PIN AG25  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[12]
set_property -dict { PACKAGE_PIN AJ24  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[13]
set_property -dict { PACKAGE_PIN AG24  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[14]
set_property -dict { PACKAGE_PIN AH22  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[15]
set_property -dict { PACKAGE_PIN AK22  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[16]
set_property -dict { PACKAGE_PIN AL22  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[17]
set_property -dict { PACKAGE_PIN AM20  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[18]
set_property -dict { PACKAGE_PIN AL23  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[19]
set_property -dict { PACKAGE_PIN AK23  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[20]
set_property -dict { PACKAGE_PIN AL25  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[21]
set_property -dict { PACKAGE_PIN AL20  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[22]
set_property -dict { PACKAGE_PIN AL24  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[23]
set_property -dict { PACKAGE_PIN AM22  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[24]
set_property -dict { PACKAGE_PIN AP24  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[25]
set_property -dict { PACKAGE_PIN AN22  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[26]
set_property -dict { PACKAGE_PIN AN24  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[27]
set_property -dict { PACKAGE_PIN AN23  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[28]
set_property -dict { PACKAGE_PIN AP25  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[29]
set_property -dict { PACKAGE_PIN AP23  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[30]
set_property -dict { PACKAGE_PIN AM24  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[31]
set_property -dict { PACKAGE_PIN AM26  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[32]
set_property -dict { PACKAGE_PIN AJ28  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[33]
set_property -dict { PACKAGE_PIN AM27  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[34]
set_property -dict { PACKAGE_PIN AK28  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[35]
set_property -dict { PACKAGE_PIN AH27  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[36]
set_property -dict { PACKAGE_PIN AH28  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[37]
set_property -dict { PACKAGE_PIN AK26  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[38]
set_property -dict { PACKAGE_PIN AK27  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[39]
set_property -dict { PACKAGE_PIN AN28  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[40]
set_property -dict { PACKAGE_PIN AM30  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[41]
set_property -dict { PACKAGE_PIN AP28  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[42]
set_property -dict { PACKAGE_PIN AM29  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[43]
set_property -dict { PACKAGE_PIN AN27  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[44]
set_property -dict { PACKAGE_PIN AL30  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[45]
set_property -dict { PACKAGE_PIN AL29  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[46]
set_property -dict { PACKAGE_PIN AP29  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[47]
set_property -dict { PACKAGE_PIN AK31  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[48]
set_property -dict { PACKAGE_PIN AH34  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[49]
set_property -dict { PACKAGE_PIN AK32  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[50]
set_property -dict { PACKAGE_PIN AJ31  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[51]
set_property -dict { PACKAGE_PIN AJ30  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[52]
set_property -dict { PACKAGE_PIN AH31  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[53]
set_property -dict { PACKAGE_PIN AJ34  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[54]
set_property -dict { PACKAGE_PIN AH32  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[55]
set_property -dict { PACKAGE_PIN AN31  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[56]
set_property -dict { PACKAGE_PIN AL34  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[57]
set_property -dict { PACKAGE_PIN AN32  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[58]
set_property -dict { PACKAGE_PIN AN33  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[59]
set_property -dict { PACKAGE_PIN AM32  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[60]
set_property -dict { PACKAGE_PIN AM34  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[61]
set_property -dict { PACKAGE_PIN AP31  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[62]
set_property -dict { PACKAGE_PIN AP33  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQ[63]

set_property -dict { PACKAGE_PIN AD21  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DM[0]
set_property -dict { PACKAGE_PIN AE25  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DM[1]
set_property -dict { PACKAGE_PIN AJ21  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DM[2]
set_property -dict { PACKAGE_PIN AM21  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DM[3]
set_property -dict { PACKAGE_PIN AH26  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DM[4]
set_property -dict { PACKAGE_PIN AN26  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DM[5]
set_property -dict { PACKAGE_PIN AJ29  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DM[6]
set_property -dict { PACKAGE_PIN AL32  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DM[7]

set_property -dict { PACKAGE_PIN AG21  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQS[0]_P
set_property -dict { PACKAGE_PIN AH21  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQS[0]_N
set_property -dict { PACKAGE_PIN AH24  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQS[1]_P
set_property -dict { PACKAGE_PIN AJ25  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQS[1]_N
set_property -dict { PACKAGE_PIN AJ20  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQS[2]_P
set_property -dict { PACKAGE_PIN AK20  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQS[2]_N
set_property -dict { PACKAGE_PIN AP20  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQS[3]_P
set_property -dict { PACKAGE_PIN AP21  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQS[3]_N
set_property -dict { PACKAGE_PIN AL27  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQS[4]_P
set_property -dict { PACKAGE_PIN AL28  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQS[4]_N
set_property -dict { PACKAGE_PIN AN29  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQS[5]_P
set_property -dict { PACKAGE_PIN AP30  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQS[5]_N
set_property -dict { PACKAGE_PIN AH33  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQS[6]_P
set_property -dict { PACKAGE_PIN AJ33  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQS[6]_N
set_property -dict { PACKAGE_PIN AN34  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQS[7]_P
set_property -dict { PACKAGE_PIN AP34  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_DQS[7]_N

set_property -dict { PACKAGE_PIN AG14  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_A0
set_property -dict { PACKAGE_PIN AF17  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_A1
set_property -dict { PACKAGE_PIN AF15  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_A2
set_property -dict { PACKAGE_PIN AJ14  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_A3
set_property -dict { PACKAGE_PIN AD18  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_A4
set_property -dict { PACKAGE_PIN AG17  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_A5
set_property -dict { PACKAGE_PIN AE17  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_A6
set_property -dict { PACKAGE_PIN AK18  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_A7
set_property -dict { PACKAGE_PIN AD16  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_A8
set_property -dict { PACKAGE_PIN AH18  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_A9
set_property -dict { PACKAGE_PIN AD19  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_A10
set_property -dict { PACKAGE_PIN AD15  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_A11
set_property -dict { PACKAGE_PIN AH16  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_A12
set_property -dict { PACKAGE_PIN AL17  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_A13
set_property -dict { PACKAGE_PIN AG15  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_BA0
set_property -dict { PACKAGE_PIN AL18  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_BA1
set_property -dict { PACKAGE_PIN AJ15  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_BG0
set_property -dict { PACKAGE_PIN AL15  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_WE_B
set_property -dict { PACKAGE_PIN AM19  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_RAS_B
set_property -dict { PACKAGE_PIN AL19  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_CAS_B
set_property -dict { PACKAGE_PIN AJ16  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_CKE
set_property -dict { PACKAGE_PIN AF18  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_ACT_B
set_property -dict { PACKAGE_PIN AE15  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_CLK_N
set_property -dict { PACKAGE_PIN AE16  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_CLK_P
set_property -dict { PACKAGE_PIN AE18  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_CS_B
set_property -dict { PACKAGE_PIN AG19  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_OTD
set_property -dict { PACKAGE_PIN AF14  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_PAR
set_property -dict { PACKAGE_PIN AG16  IOSTANDARD SSTL15 } [get_ports { PL_DDR4_RST